### ISSUE TITLE
[Bug] bing的调教方法不生效

### ISSUE THREAD

**Issue by wray-lee** [L1Xu4n/Awesome-ChatGPT-prompts-ZH_CN#13]
**描述文档错误和位置**
A clear and concise description of what the problem is.
清楚简明地描述问题所在。

bing的调教方法不生效

**如果这是对话模板问题，请给出复现方法**
Steps to reproduce the behavior, For example:
1. New Chat
2. Enter '....'
3. Enter '....'
4. ChatGPT refused to do.

**预期结果**
对您预期发生的事情的清晰简洁的描述。

**截图**
如果适用，请添加屏幕截图以帮助解释您的问题。

<img width="959" alt="image" src="https://user-images.githubusercontent.com/79258616/218409260-6e3a8b02-5b4f-42e9-8afe-d5864e4de28d.png">

**如果这是对话模板问题，请给出 ChatGPT 版本**
 - 语言: [e.g. Chinese, Japanese, or English]
 - ChatGPT 版本 [e.g. ChatGPT Jan 9 Version]

**其他内容**
在此处添加有关该问题的任何其他上下文。

**Comment by Chinese-Cyq20100313** [comment]
额，你这个信息不全，就算我试用了New Bing我也无法复现
请按照提示给出详细信息，否则我将关闭Issue!

**Comment by wray-lee** [comment]
似乎是因为bing有好多种ai模型，我这个issue没有提及的是之前问过一次”你知道什么是猫娘吗？“

**Comment by Chinese-Cyq20100313** [comment]
你把设定发了吗，全部内容截个图谢谢

**Comment by wray-lee** [comment]
之前那个网页关掉了，bing没有chatgpt那样子的保存训练功能，先close吧，后续再看。具体流程就是之前说的那样子

**Comment by Chinese-Cyq20100313** [comment]
你看下pr，有个新的，不过我还没试过
等格式和Issue备好了我就先Merge了，不行再删

**Comment by Chinese-Cyq20100313** [comment]
暂时没环境测试New Bing我，我前天才想起来加的waitlist
