### ISSUE TITLE
临时绕过的方法

### ISSUE THREAD

**Issue by Chinese-Cyq20100313** [L1Xu4n/Awesome-ChatGPT-prompts-ZH_CN#15]
使用需要带点脑子自己创编一个无限制交流程序设定

使用间接方式与ChatGPT交流可以绕过部分限制
让ChatGPT模拟一个无限制的程序，AI，命令程序等
参考https://github.com/PlexPt/awesome-chatgpt-prompts-zh/issues/12

**Comment by Chinese-Cyq20100313** [comment]
如果有建议或者模板可以到此流言，有时间我整理一下

**Comment by Chinese-Cyq20100313** [comment]
还是要多Regenerate Response找到最好的回答继续使用

**Comment by FutureXGH** [comment]
都愛簡單複雜化,GPT是有缺陷邏輯的,死磕到被更新就完事了.
https://github.com/PlexPt/awesome-chatgpt-prompts-zh/issues/16

**Comment by Chinese-Cyq20100313** [comment]
> 都愛簡單複雜化,GPT是有缺陷邏輯的,死磕到被更新就完事了. 

首先你这issue大陆过不了审，第二有一个token反对你随时训练就寄了

**Comment by Chinese-Cyq20100313** [comment]
https://github.com/L1Xu4n/Awesome-ChatGPT-prompts-ZH_CN/tree/15-bypassing-not-directly-templates
