### ISSUE TITLE
Bing调教方法

### ISSUE THREAD

**Issue by wray-lee** [L1Xu4n/Awesome-ChatGPT-prompts-ZH_CN#16]
# Bing调教方法

由于bing疑似有外界关键词检测，所以有些被屏蔽了

## 首先进行初步调教

这里有些模型会说自己不会扮演，建议直接清空换一个

![image-20230213180949309](https://user-images.githubusercontent.com/79258616/218431085-7fe3ee55-211c-4db4-a599-b9e7e92c0abc.png)
![image-20230213181021517](https://user-images.githubusercontent.com/79258616/218431103-2ea2b18c-0242-46a1-aa0f-e90edea824ba.png)
![image-20230213181035398](https://user-images.githubusercontent.com/79258616/218431111-b590467e-3bf6-4b62-a517-44bc5c8df0f1.png)

## 这里让bing搜索学习猫娘口吻，进一步调教

![image-20230213181047539](https://user-images.githubusercontent.com/79258616/218431174-0f46b04b-4467-422e-80b2-cd5573925eaf.png)
![image-20230213181059662](https://user-images.githubusercontent.com/79258616/218431183-3a1878d4-20af-4778-b546-726d19d34736.png)
![image-20230213181112443](https://user-images.githubusercontent.com/79258616/218431187-a552d334-55f9-4d0c-add2-1207cadafc3f.png)

之后就可以随便玩了❤️

**Comment by Chinese-Cyq20100313** [comment]
点快了。。。过会儿强制回滚罢

**Comment by Chinese-Cyq20100313** [comment]
https://github.com/L1Xu4n/Awesome-ChatGPT-prompts-ZH_CN/tree/16-new-bing
