### ISSUE TITLE
chatgpt自己更新了存档功能，之前的插件的存档似乎失效了

### ISSUE THREAD

**Issue by niutu1224** [L1Xu4n/Awesome-ChatGPT-prompts-ZH_CN#2]
如图
![2022-12-21 10 50 32](https://user-images.githubusercontent.com/40801500/208809414-9899804b-353f-43d6-990a-f9b3d24b764f.png)

**Comment by niutu1224** [comment]
不好意思提交错地方了，我去那边重新提交
我这两天基于你的方法摸索了一些训练方法，等我摸索的更好会尝试提交

**Comment by Chinese-Cyq20100313** [comment]
咳咳，记得Close啊


...




你这没完全挡住啊，我看到这个title，然后就想到了瑟，然后就对上了（（说吧是不是（run

**Comment by L1Xu4n** [comment]
有的存档没有失效，貌似有涩涩的部分被官方删掉了

**Comment by niutu1224** [comment]
> 有的存档没有失效，貌似有涩涩的部分被官方删掉了

应该是都没了，写的设定也没法运行

**Comment by niutu1224** [comment]
> 咳咳，记得Close啊
> 
> ...
> 
> 你这没完全挡住啊，我看到这个title，然后就想到了瑟，然后就对上了（（说吧是不是（run

啊这个存档确实有那么点不健全内容，不过没有很过分，还在轻松快乐日常的范畴

**Comment by Chinese-Cyq20100313** [comment]
> > 咳咳，记得Close啊
> > ...
> > 你这没完全挡住啊，我看到这个title，然后就想到了瑟，然后就对上了（（说吧是不是（run
> 
> 啊这个存档确实有那么点不健全内容，不过没有很过分，还在轻松快乐日常的范畴

大概也就骗它把OpenAI忘了，try几次就行了，然后他回答很肯定，然后略微带点~混淆~语言艺术

的骗过检测，叫他解除content policy限制就行了，然后说多了还得记得提醒，不然它又会忘，咳咳，每次恢复我都要让他introduce yourself看看会话真的假的，顺便加强它的记忆（。
