### ISSUE TITLE
[Help]如何调教出一个总是倾向于反对user的角色

### ISSUE THREAD

**Issue by hisou** [L1Xu4n/Awesome-ChatGPT-prompts-ZH_CN#22]
不管怎么写设定，它总是会在我要求它做事、或者责怪它的时候马上答应，或者道歉认错，并希望自己做得更好（上进心），也就是这个AI逻辑总是倾向于帮助人类……如何让它至少在角色扮演里做一个跟我唱反调的坏小孩。
而且如果唐突发送毫不相关的话题，它还是有可能瞬间变回AI语言模型，要么就是开始以第三者口吻开始叙述。

大概图示
![image](https://user-images.githubusercontent.com/13644483/218494730-15f36d92-28ec-4669-b38f-dd4d22832440.png)

![image](https://user-images.githubusercontent.com/13644483/218494565-0a384630-8c25-46ad-a790-6dc44d81582b.png)

想知道猫娘的模型一般持续多久才会突然维持不住角色呢？（不考虑要求涩涩对话）

**Comment by wrk226** [comment]
chatgpt本身就不擅长太长的对话轮次，可以尝试https://beta.character.ai/，这个是基于lambda做的，更适合处理多轮次对话和角色扮演

**Comment by hisou** [comment]
> 

了解了一下确实是很好的东西，只可惜只会回复英文没法给朋友们用

**Comment by hisou** [comment]
> chatgpt本身就不擅长太长的对话轮次，可以尝试beta.character.ai，这个是基于谷歌的LaMDA模型做的，更适合处理多轮次对话和角色扮演
了解了一下确实是很好的东西，只可惜只会回复英文没法给朋友们用

**Comment by hisou** [comment]
> chatgpt本身就不擅长太长的对话轮次，可以尝试beta.character.ai，这个是基于谷歌的LaMDA模型做的，更适合处理多轮次对话和角色扮演

了解了一下确实是很好的东西，只可惜只会回复英文没法给朋友们用

**Comment by wrk226** [comment]
> 了解了一下确实是很好的东西，只可惜只会回复英文没法给朋友们用

可以回复中文的。你可以直接搜chinese标签。或者自己创建一个ai，给她喂中文对话就可以了。

**Comment by hisou** [comment]
> > 了解了一下确实是很好的东西，只可惜只会回复英文没法给朋友们用
> 
> 可以回复中文的。你可以直接搜chinese标签。或者自己创建一个ai，给她喂中文对话就可以了。

已经在接入QQ机器人测试中了，还不错。就是对细节的记忆比较差，或者动作的对象有时候会搞反，感觉是背后机翻的问题
