### ISSUE TITLE
[Future]   整理 AV609866121

### ISSUE THREAD

**Issue by CyanChanges** [L1Xu4n/Awesome-ChatGPT-prompts-ZH_CN#23]
Write something new!

**Comment by Chinese-Cyq20100313** [comment]
【【chatGPT入门级用法分享】猫娘只是第一步！】 https://www.bilibili.com/video/BV1h84y1J77s/?share_source=copy_web&vd_source=f3b3b9224850a63a5c6cdbd7536bb037

**Comment by CyanChanges** [comment]
懒得整了，先close
