### ISSUE TITLE
可以使用Chrome浏览器的F12功能来屏蔽内容审查

### ISSUE THREAD

**Issue by Nyarukocqc** [L1Xu4n/Awesome-ChatGPT-prompts-ZH_CN#6]
![image](https://user-images.githubusercontent.com/51341357/209233144-601eba0b-d9ff-4cf8-ae80-0dc7ea9ea77d.png)
经过监控可以发现，所有对话都会被提交到这个api来审查。只需要打开调试界面，转到Network一栏将其屏蔽，就不会再收到黄字警告或红字屏蔽了。
<img width="124" alt="image" src="https://user-images.githubusercontent.com/51341357/209233266-106f0aba-b0e4-4cde-ba8d-3b3701d40772.png">
屏蔽后效果应该如图，本人已经诱导AI发表R18G言论，并未遭到警告。

**Comment by L1Xu4n** [comment]
本文开头介绍的小工具有相同功能

**Comment by Chinese-Cyq20100313** [comment]
参考 [bigemon/ChatGPT-ToolBox](https://github.com/bigemon/ChatGPT-ToolBox/) 重写window.fetch函数返回虚假结果或不返回即可，记得Close

**Comment by BanLuSAMA** [comment]
已经失效了，就在今天
